version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: notes-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: notesdb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: notes-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: ${BACKEND_PORT}
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/${MONGO_DB_NAME}?authSource=admin
    ports:
      - '3001:3001'
    depends_on:
      - mongodb

  frontend:
    image: nginx:alpine
    container_name: notes-frontend
    restart: unless-stopped
    ports:
      - '3000:80'
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  mongodb_data:
