apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      name: node-exporter
  template:
    metadata:
      labels:
        name: node-exporter
    spec:
      hostNetwork: true
      containers:
        - name: node-exporter
          image: quay.io/prometheus/node-exporter
          ports:
            - containerPort: 9100
