apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  labels:
    prometheus: server
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-apiservers'
        kubernetes_sd_configs:
        - role: endpoints
        scheme: https
      - job_name: 'kubernetes-nodes'
        kubernetes_sd_configs:
        - role: node
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
        - role: pod
      - job_name: 'kube-state-metrics'
        kubernetes_sd_configs:
        - role: endpoints
        relabel_configs:
        - source_labels: [__meta_kubernetes_namespace]
          action: keep
          regex: monitoring
      - job_name: 'fluentd'
        static_configs:
        - targets: ['fluentd.kube-system:24231']
