apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-pods
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend-pods
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: notes_frontend
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: database-pods
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: notes_database
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
