# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: <deployment-name>      # Name of the deployment
#   labels:                      # Optional metadata
#     app: <app-name>
# spec:
#   replicas: <number>           # How many pods to run
#   selector:
#     matchLabels:               # Must match pod template labels
#       app: <app-name>
#   template:                    # Pod template (what each pod looks like)
#     metadata:
#       labels:
#         app: <app-name>
#     spec:
#       containers:              # List of containers in the pod
#       - name: <container-name>
#         image: <image-name:tag>
#         ports:
#         - containerPort: <port-inside-container>
#         env:                   # Optional: Environment variables (can come from secrets/configmaps)
#         - name: <ENV_NAME>
#           value: <value>

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: notes-backend-container
          image: thetharz/k8s-demo-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGODB_URI
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: PORT
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_ROOT_PASSWORD
