# apiVersion: v1
# kind: Secret
# metadata:
#   name: <secret-name>   # name of your secret
# type: Opaque            # type Opaque = generic secret
# data:                   # key-value pairs (must be base64 encoded)
#   <key>: <base64-value>
#   <key2>: <base64-value>

# kubectl apply -f secrets.yaml

# kubectl get secrets

# echo -n 'admin' | base64

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  MONGO_ROOT_USERNAME: cm9vdA==
  MONGO_ROOT_PASSWORD: cm9vdA==
  PORT: MzAwMQ== # 3001
  MONGODB_URI: bW9uZ29kYjovL3Jvb3Q6cm9vdEBkYXRhYmFzZToyNzAxNy9ub3Rlc2RiP2F1dGhTb3VyY2U9YWRtaW4=
  NODE_ENV: cHJvZHVjdGlvbg== # THis also can be put inside a config map
