apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: notes_frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes_frontend
  template:
    metadata:
      labels:
        app: notes_frontend
    spec:
      containers:
        - name: notes-frontend-container
          image: thetharz/k8s-demo-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 1Gi
          env:
            - name: API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: frontend-secrets
                  key: API_BASE_URL
