apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: notes_frontend
spec:
  type: NodePort
  selector:
    app: notes_frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
