apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: notes_database
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notes_database
  template:
    metadata:
      labels:
        app: notes_database
    spec:
      containers:
        - name: notes-database-container
          image: mongo:7.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: MONGO_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-secrets
                  key: DATABASE
