apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: notes-backend-vpa
spec:
  targetRef:
    apiVersion: 'apps/v1'
    kind: Deployment
    name: notes-backend
  updatePolicy:
    updateMode: 'Auto'
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: notes-frontend-vpa
spec:
  targetRef:
    apiVersion: 'apps/v1'
    kind: Deployment
    name: frontend
  updatePolicy:
    updateMode: 'Auto'
